### ISSUE TITLE
More routines

### ISSUE THREAD

**Issue by mike2505** [tzebrowski/ObdMetrics#14]
Hello,

Where can I get more routines? [Based on this](https://www.giuliaforums.com/threads/opensource-performance-monitor-for-android-auto.63770/?post_id=1080509&nested_view=1&sortby=oldest#post-1080509) thread on giulia forum, there must be a routine for Dyno\Roll bench mode as well as front axle control..

Thanks!

**Comment by tzebrowski** [comment]
What do you mean ?
